version: '3.8'

services:
  webserver:
    image: "registry.reitetschlaeger.com/blocklist-webserver:latest"
#    build:
#      context: .
#      dockerfile: dockerfile.app
    ports:
      - "5000:5000"
    environment:
      TZ: "Europe/Vienna"
      REDIS_HOST: redis
      LOGWEB: "true"
      SECRET_KEY: "XXXXXXXX---SECRET_KEY----"
      #Webhook Block Range // Whitelist
      BLOCKED_RANGES: "127.0.0.1/32, 0.0.0.0/32, 192.168.0.0/16, 10.0.0.0/8, 172.12.0.0/12, 193.104.82.0/24, 80.66.59.216/32, 83.164.150.0/24, 1.1.1.1/32, 1.0.0.1/32, 8.8.8.8/32, 8.8.4.4/32, 13.107.6.152/31, 13.107.18.10/31, 13.107.128.0/22, 23.103.160.0/20, 40.96.0.0/13, 40.104.0.0/15, 52.96.0.0/14, 131.253.33.215/32, 132.245.0.0/16, 150.171.32.0/22, 204.79.197.215/32, 40.92.0.0/15, 40.107.0.0/16, 52.100.0.0/14, 52.238.78.88/32, 104.47.0.0/17, 13.107.136.0/22, 40.108.128.0/17, 52.104.0.0/14, 104.146.128.0/17, 150.171.40.0/22, 13.107.64.0/18, 52.112.0.0/14, 52.122.0.0/15, 52.238.119.141/32, 52.244.160.207/32, 13.107.6.171/32, 13.107.18.15/32, 13.107.140.6/32, 52.108.0.0/14, 52.244.37.168/32, 81.201.100.224/27, 81.201.101.192/26, 154.52.10.0/24, 173.243.0.0/16, 208.91.113.0/24, 208.91.113.0/24, 173.243.132.0/24"
      GUIAdmin: admin
      GUIPassword: "XXXXXXXX---SECRET_PASSWORD----"
      GUIToken: XXXXXXXX---SECRET_TOKEN----
      USER1: "user1"
      UPW1: "XXXXXXXX---SECRET_KEY----"
      USER2: "user2"
      UPW2: "XXXXXXXX---SECRET_KEY----"
    volumes:
      - '/<path>/geoipupdate_data:/usr/share/GeoIP'
    depends_on:
      - redis
    networks:
      - free1_default
    restart: unless-stopped
  scheduler:
    image: "registry.reitetschlaeger.com/blocklist-scheduler:latest"
    environment:
      TZ: "Europe/Vienna"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      LOGWEB: true
    depends_on:
      - redis
    networks:
      - free1_default
    restart: unless-stopped
  redis:
    image: "redis:alpine"
    networks:
      - free1_default
    restart: unless-stopped
  geoipupdate:
    image: ghcr.io/maxmind/geoipupdate
    restart: unless-stopped
    environment:
      - GEOIPUPDATE_ACCOUNT_ID=671928
      - GEOIPUPDATE_LICENSE_KEY=XXXXXXXX---SECRET_LICENSEKEY----
      - 'GEOIPUPDATE_EDITION_IDS=GeoLite2-ASN GeoLite2-City GeoLite2-Country'
      - GEOIPUPDATE_FREQUENCY=72
    networks:
      - free1_default
    volumes:
      - '/<path>/geoipupdate_data:/usr/share/GeoIP'

networks:
  free1_default:
    external: true
