version: '3.8'

services:
  webserver:
    image: "registry.reitetschlaeger.com/blocklist-webserver:latest"
    ports:
      - "5000:5000"
    environment:
      TZ: "Europe/Vienna"
      REDIS_HOST: redis
      LOGWEB: "true"
      SECRET_KEY: "XXXXXXXX---SECRET_KEY----"
      #Webhook Block Range // Whitelist
      BLOCKED_RANGES: "127.0.0.1/32, 0.0.0.0/32, 192.168.0.0/16, 10.0.0.0/8, 172.12.0.0/12"
      GUIAdmin: admin
      GUIPassword: "XXXXXXXX---SECRET_PASSWORD----"
      GUIToken: XXXXXXXX---SECRET_TOKEN----
      USER1: "user1"
      UPW1: "XXXXXXXX---SECRET_KEY----"
      USER2: "user2"
      UPW2: "XXXXXXXX---SECRET_KEY----"
    volumes:
      - '/<path>/geoipupdate_data:/usr/share/GeoIP'
    depends_on:
      - redis
    networks:
      - free1_default
    restart: unless-stopped
  scheduler:
    image: "registry.reitetschlaeger.com/blocklist-scheduler:latest"
    environment:
      TZ: "Europe/Vienna"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      LOGWEB: true
    depends_on:
      - redis
    networks:
      - free1_default
    restart: unless-stopped
  redis:
    image: "redis:alpine"
    networks:
      - free1_default
    restart: unless-stopped
  geoipupdate:
    image: ghcr.io/maxmind/geoipupdate
    restart: unless-stopped
    environment:
      - GEOIPUPDATE_ACCOUNT_ID=671928
      - GEOIPUPDATE_LICENSE_KEY=XXXXXXXX---SECRET_LICENSEKEY----
      - 'GEOIPUPDATE_EDITION_IDS=GeoLite2-ASN GeoLite2-City GeoLite2-Country'
      - GEOIPUPDATE_FREQUENCY=72
    networks:
      - free1_default
    volumes:
      - '/<path>/geoipupdate_data:/usr/share/GeoIP'

networks:
  free1_default:
    external: true
